name: Build and Deploy
on: [push]
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'deploy')
    steps:
      - name: Checkout code 👀
        uses: actions/checkout@v3

      - name: Install dependencies 📦
        working-directory: ./ # Specify the folder where the app code resides (./client for fullstack applications).
        run: npm ci # Clean install of the project's dependencies.

      # Build the application
      - name: Build the app 🏗️
        working-directory: ./
        run: npm run build # Runs the 'build' script defined in the package.json file

      # Configure the GitHub Pages deployment
      - name: Setup Pages 📃
        uses: actions/configure-pages@v4

      # Uploads the build output for deployment to GitHub Pages.
      - name: Upload artifact ⬆️
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist" # Path to the built app's static files, this can be configured in the `vite.config` file with 'outputDir'

      # Deploy the application to GitHub Pages using the 'deploy-pages' pre-build action.
      - name: Deploy to GitHub Pages ✨
        id: deployment
        uses: actions/deploy-pages@v4
